### ISSUE TITLE
can cv 'upgrade' an extension?

### ISSUE THREAD

**Issue by lsh-0** [civicrm/cv#33]
I'm trying to pin specific versions of custom extensions installed and automate their upgrade.

With `cv`, I was doing this:

`cv dl "longname@https://path/to/archive/V0.1.zip" --no-interaction --force`

this would uninstall and reinstall a custom extension. 

I now have an extension (emailapi) that isn't being uninstalled cleanly and I get a stacktrace when the creation of a trigger is attempted again:

```
Error: API Call Failed: Array
(
    [entity] => Extension
    [action] => download
    [params] => Array
        (
            [key] => org.civicoop.emailapi
            [url] => https://github.com/CiviCooP/org.civicoop.emailapi/archive/V1.12.zip
            [install] => 1
            [debug] => 1
            [version] => 3
        )

    [result] => Array
        (
            [trace] => #0 /srv/crm-project/crm/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(234): CRM_Core_ManagedEntities->onApiError('CiviRuleTrigger', 'create', Array, Array)
#1 /srv/crm-project/crm/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(179): CRM_Core_ManagedEntities->insertNewEntity(Array)
#2 /srv/crm-project/crm/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(141): CRM_Core_ManagedEntities->reconcileEnabledModule(Object(CRM_Core_Module), Array)
#3 /srv/crm-project/crm/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(122): CRM_Core_ManagedEntities->reconcileEnabledModules()
#4 /srv/crm-project/crm/sites/all/modules/civicrm/CRM/Core/Invoke.php(395): CRM_Core_ManagedEntities->reconcile()
#5 /srv/crm-project/crm/sites/all/modules/civicrm/CRM/Extension/Manager.php(196): CRM_Core_Invoke::rebuildMenuAndCaches(true)
#6 /srv/crm-project/crm/sites/all/modules/civicrm/CRM/Extension/Downloader.php(126): CRM_Extension_Manager->replace('/tmp/tmp-DHBZML...')
#7 /srv/crm-project/crm/sites/all/modules/civicrm/api/v3/Extension.php(242): CRM_Extension_Downloader->download('org.civicoop.em...', 'https://github....')
#8 /srv/crm-project/crm/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_extension_download(Array)
#9 /srv/crm-project/crm/sites/all/modules/civicrm/Civi/API/Kernel.php(174): Civi\API\Provider\MagicFunctionProvider->invoke(Array)
#10 /srv/crm-project/crm/sites/all/modules/civicrm/Civi/API/Kernel.php(100): Civi\API\Kernel->runRequest(Array)
#11 /srv/crm-project/crm/sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->runSafe('Extension', 'download', Array, NULL)
#12 phar:///usr/local/bin/cv/src/Command/BaseCommand.php(43): civicrm_api('Extension', 'download', Array)
#13 phar:///usr/local/bin/cv/src/Command/ExtensionDownloadCommand.php(146): Civi\Cv\Command\BaseCommand->callApiSuccess(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), 'Extension', 'download', Array)
#14 phar:///usr/local/bin/cv/vendor/symfony/console/Command/Command.php(257): Civi\Cv\Command\ExtensionDownloadCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(850): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Civi\Cv\Command\ExtensionDownloadCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar:///usr/local/bin/cv/vendor/symfony/console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 phar:///usr/local/bin/cv/src/Application.php(17): Symfony\Component\Console\Application->run()
#19 phar:///usr/local/bin/cv/bin/cv(26): Civi\Cv\Application::main('phar:///usr/loc...')
#20 /usr/local/bin/cv(10): require('phar:///usr/loc...')
#21 {main}
            [is_error] => 1
            [error_message] => API error: There is already a trigger for this class_name or combination of object_name and op
        )

)
```

I imagine the GUI wouldn't let you click the upgrade button for an extension if upgrades weren't available.

Short of elaborate scripting, can `cv` be told to upgrade if an upgrade is available? or if a flag like `--upgrade` is present?

I imagine the logic for the above command would go like this:

```
$ cv dl "longname@https://path/to/archive/V0.1.zip" --no-interaction --upgrade
* downloads archive at given path
* compares version to installed version
* if two versions are identical, halt
* else, install new version
```

the current logic for

`$ cv dl "longname@https://path/to/archive/V0.1.zip" --no-interaction`

(install if not installed, else skip) and

`$ cv dl "longname@https://path/to/archive/V0.1.zip" --no-interaction --force`

(install regardless) seems fine to me.

**Comment by lsh-0** [comment]
closing this. the above error is due to an extension (civirules) breaking the installation/enabling of all other extensions: https://github.com/CiviCooP/org.civicoop.civirules/issues/180

**Comment by totten** [comment]
OK. Good investigation.
